### ISSUE TITLE
SpoonInstall Install automatically from this git repo?

### ISSUE THREAD

**Issue by andrewcrook** [ozguncagri/OzzyWM#2]
I cannot seem to add OzzyWM git repo as a spoon repo. It cannot find a repo or the spoons. 
Tbh I am not sure how a spoon repo is defined exactly.

```lua
-- Spoon manager
 hs.loadSpoon("SpoonInstall")
 Install = spoon.SpoonInstall
 spoon.SpoonInstall.repos.OzzyWM = {
    url = "https://github.com/ozguncagri/OzzyWM",
   desc = "Multi-screen window manager plugin for Hammerspoon",
 }

 Install:andUse('ShiftIt')
```

I have also tried to download the release zip directly from GitHub using SpoonInstall installSpoonFromZipURL. 
However, its not detecting a spoon in the file.

init.lua

``` lua
-- Spoon manager
hs.loadSpoon("SpoonInstall")
Install = spoon.SpoonInstall
Install:installSpoonFromZipURL('https://github.com/ozguncagri/OzzyWM/releases/latest/download/OzzyWM.spoon.zip’)
```

Result 

```text
ERROR:SpoonInsta: The downloaded zip file /var/folders/tg/wd1yw6m12mz7vyb1nw2wz9n80000gn/T/tmp.v7avQtsO/OzzyWM.spoon.zip is invalid - it should contain exactly one spoon. Leaving it in place for your examination.
```

**Comment by ozguncagri** [comment]
Hey @andrewcrook

I wasn't event know there is a SpoonInstall because I created this plug-in long time ago and wasn't using mac for a while. I think you can install it manually by following [Installation](https://github.com/ozguncagri/OzzyWM#installation) section on readme file.

SpoonInstall may require some additional formatting or packing which I have no information right now but I'll check it later if I have time.
